# INSERT INTO platform
INSERT INTO platform(id, name) VALUES (1,"Nintendo 64");
INSERT INTO platform(id, name) VALUES (2,"PlayStation");
INSERT INTO platform(id, name) VALUES (3,"PlayStation 3");
INSERT INTO platform(id, name) VALUES (4,"Dreamcast");
INSERT INTO platform(id, name) VALUES (5,"Xbox 360");
INSERT INTO platform(id, name) VALUES (6,"Wii");
INSERT INTO platform(id, name) VALUES (7,"Xbox One");
INSERT INTO platform(id, name) VALUES (8,"PC");
INSERT INTO platform(id, name) VALUES (9,"Switch");
INSERT INTO platform(id, name) VALUES (10,"PlayStation 2");
INSERT INTO platform(id, name) VALUES (11,"PlayStation 4");
INSERT INTO platform(id, name) VALUES (12,"GameCube");
INSERT INTO platform(id, name) VALUES (13,"Xbox");
INSERT INTO platform(id, name) VALUES (14,"Wii U");
INSERT INTO platform(id, name) VALUES (15,"Game Boy Advance");
INSERT INTO platform(id, name) VALUES (16,"3DS");
INSERT INTO platform(id, name) VALUES (17,"Xbox Series X");
INSERT INTO platform(id, name) VALUES (18,"DS");
INSERT INTO platform(id, name) VALUES (19,"PlayStation Vita");
INSERT INTO platform(id, name) VALUES (20,"PlayStation 5");
INSERT INTO platform(id, name) VALUES (21,"PSP");
INSERT INTO platform(id, name) VALUES (22,"Stadia");
